version: '3.8'
services:
  gateway:
    build: gateway
    container_name: share_it_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    container_name: share_it_server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share_it_db_docker
      - SPRING_DATASOURCE_USERNAME=db_docker
      - SPRING_DATASOURCE_PASSWORD=db_docker

  db:
    image: postgres:14-alpine
    container_name: share_it_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share_it_db_docker
      - POSTGRES_USER=db_docker
      - POSTGRES_PASSWORD=db_docker